// SPDX-License-Identifier: 0BSD
package rnv

import "errors"

var (
	ErrNilArgument       = errors.New("rnv: nil argument")
	ErrBadFieldLength    = errors.New("rnv: bad field length")
	ErrWrongVersion      = errors.New("rnv: wrong protocol version")
	ErrPacketTooLarge    = errors.New("rnv: packet too large")
	ErrEnvelopeTooLarge  = errors.New("rnv: envelope too large")
	ErrStillTooLarge     = errors.New("rnv: still exceeds size limit")
	ErrClipTooLarge      = errors.New("rnv: clip exceeds size limit")
	ErrFrameTooLarge     = errors.New("rnv: frame exceeds size limit")
	ErrBadDimensions     = errors.New("rnv: dimensions exceed limits")
	ErrCapacity          = errors.New("rnv: peer or profile cannot sustain offer")
	ErrRejected          = errors.New("rnv: peer rejected")
	ErrSessionClosed     = errors.New("rnv: session closed")
	ErrLinkInactive      = errors.New("rnv: link inactive")
	ErrDialTimeout       = errors.New("rnv: dial timeout")
	ErrHelloTimeout      = errors.New("rnv: hello timeout")
	ErrNotHandshaken     = errors.New("rnv: handshake incomplete")
	ErrStreamNotOpen     = errors.New("rnv: stream not open")
	ErrStreamAlreadyOpen = errors.New("rnv: stream already open")
	ErrClipNotAccepted   = errors.New("rnv: clip not accepted")
	ErrProgressRequired  = errors.New("rnv: progress callback required for large clip")
	ErrParallelLXST      = errors.New("rnv: parallel LXST call blocked (set AllowParallelLXST)")
	ErrUnknownExtension  = errors.New("rnv: unknown extension in strict mode")
	ErrUnknownCodec      = errors.New("rnv: unknown codec")
	ErrVideoTrackDenied  = errors.New("rnv: video track not allowed at this profile")
	ErrAudioTrackDenied  = errors.New("rnv: audio track not allowed at this profile")
	ErrInvalidOffer      = errors.New("rnv: invalid offer")
	ErrResourceFailed    = errors.New("rnv: resource transfer failed")
	ErrResourceTimeout   = errors.New("rnv: resource transfer timeout")
	ErrRateLimited       = errors.New("rnv: rate limited")
)
